# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

# Prepare React Native project
prepare_react_native_project!



# Check Flipper configuration
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']

# Configure Pods with frameworks if specified
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
end

target 'Reactivity' do
  # React Native configurations
  config = use_native_modules!

  # Include RNFBFirestore pod
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled], # Enable/disable Hermes
    :fabric_enabled => flags[:fabric_enabled], # Enable/disable Fabric
    # :flipper_configuration => flipper_config,  # Configure Flipper
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  # Target for ReactivityTests
  target 'ReactivityTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post-install configurations
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
